// Asset registry: maps asset keys to their public URL.
// Files live in frontend/public/assets/ and are generated by scripts/generate-assets.mjs.
// If an asset hasn't been generated yet, the component falls back to its emoji placeholder.
//
// To add a new asset: add the entry here, add it to scripts/asset-manifest.mjs,
// then re-run the generator.

export const ASSET_BASE = "/assets";

export type AssetKey =
  // buildings
  | "building-gate" | "building-wall" | "building-bank" | "building-well"
  | "building-workshop" | "building-tower" | "building-townhall"
  | "building-kitchen" | "building-panel" | "building-scaffold"
  // heroes
  | "hero-sans-classe" | "hero-pionnier" | "hero-chasseur" | "hero-eclaireur"
  | "hero-gardien" | "hero-recuperateur" | "hero-herboriste"
  // ui
  | "nav-home" | "nav-map" | "nav-stock" | "nav-structure" | "nav-craft"
  | "bird" | "skull"
  // npc / bg
  | "shinki-npc" | "town-island" | "app-bg" | "bridge"
  // map tiles (one per biome 0..5)
  | "tile-water" | "tile-sand" | "tile-grass" | "tile-forest" | "tile-mountain" | "tile-snow"
  // isometric cube tiles (iso Home grid + iso combat biomes)
  | "iso-water" | "iso-sand" | "iso-grass" | "iso-forest" | "iso-stone" | "iso-snow" | "iso-bridge";

const PATHS: Record<AssetKey, string> = {
  "building-gate":      `${ASSET_BASE}/buildings/gate.png`,
  "building-wall":      `${ASSET_BASE}/buildings/wall.png`,
  "building-bank":      `${ASSET_BASE}/buildings/bank.png`,
  "building-well":      `${ASSET_BASE}/buildings/well.png`,
  "building-workshop":  `${ASSET_BASE}/buildings/workshop.png`,
  "building-tower":     `${ASSET_BASE}/buildings/tower.png`,
  "building-townhall":  `${ASSET_BASE}/buildings/townhall.png`,
  "building-kitchen":   `${ASSET_BASE}/buildings/kitchen.png`,
  "building-panel":     `${ASSET_BASE}/buildings/panel.png`,
  "building-scaffold":  `${ASSET_BASE}/buildings/scaffold.png`,

  "hero-sans-classe":   `${ASSET_BASE}/heroes/hero-0.png`,
  "hero-pionnier":      `${ASSET_BASE}/heroes/hero-pionnier.png`,
  "hero-chasseur":      `${ASSET_BASE}/heroes/hero-chasseur.png`,
  "hero-eclaireur":     `${ASSET_BASE}/heroes/hero-eclaireur.png`,
  "hero-gardien":       `${ASSET_BASE}/heroes/hero-gardien.png`,
  "hero-recuperateur":  `${ASSET_BASE}/heroes/hero-recuperateur.png`,
  "hero-herboriste":    `${ASSET_BASE}/heroes/hero-herboriste.png`,

  "nav-home":      `${ASSET_BASE}/ui/nav-home.png`,
  "nav-map":       `${ASSET_BASE}/ui/nav-map.png`,
  "nav-stock":     `${ASSET_BASE}/ui/nav-stock.png`,
  "nav-structure": `${ASSET_BASE}/ui/nav-structure.png`,
  "nav-craft":     `${ASSET_BASE}/ui/nav-craft.png`,
  "bird":          `${ASSET_BASE}/ui/bird.png`,
  "skull":         `${ASSET_BASE}/ui/skull.png`,

  "shinki-npc":   `${ASSET_BASE}/npc/shinki.png`,
  "town-island":  `${ASSET_BASE}/bg/town-island.png`,
  "app-bg":       `${ASSET_BASE}/bg/app-bg.png`,
  "bridge":       `${ASSET_BASE}/bg/bridge.png`,

  "tile-water":    `${ASSET_BASE}/tiles/water.png`,
  "tile-sand":     `${ASSET_BASE}/tiles/sand.png`,
  "tile-grass":    `${ASSET_BASE}/tiles/grass.png`,
  "tile-forest":   `${ASSET_BASE}/tiles/forest.png`,
  "tile-mountain": `${ASSET_BASE}/tiles/mountain.png`,
  "tile-snow":     `${ASSET_BASE}/tiles/snow.png`,

  "iso-water":    `${ASSET_BASE}/isotiles/water.png`,
  "iso-sand":     `${ASSET_BASE}/isotiles/sand.png`,
  "iso-grass":    `${ASSET_BASE}/isotiles/grass.png`,
  "iso-forest":   `${ASSET_BASE}/isotiles/forest.png`,
  "iso-stone":    `${ASSET_BASE}/isotiles/stone.png`,
  "iso-snow":     `${ASSET_BASE}/isotiles/snow.png`,
  "iso-bridge":   `${ASSET_BASE}/isotiles/bridge.png`,
};

// Resolved set of available assets (populated at startup by probing HEAD requests).
// During SSR / before detection completes, all assets are considered unavailable
// so components fall back to their emoji placeholders.
const available = new Set<AssetKey>();

export function assetUrl(key: AssetKey): string | undefined {
  return available.has(key) ? PATHS[key] : undefined;
}

// Called once at app start. Probes which assets exist so components can switch
// from emoji fallbacks to real images.
export async function detectAvailableAssets(): Promise<void> {
  const checks = Object.entries(PATHS) as [AssetKey, string][];
  await Promise.allSettled(
    checks.map(async ([key, url]) => {
      try {
        const r = await fetch(url, { method: "HEAD" });
        if (r.ok) available.add(key);
      } catch {}
    }),
  );
}

// ── Asset library (bulk-generated set under /assets/{category}/) ──────────────────
// These aren't HEAD-probed (there are ~160 of them); reference them directly by
// category + filename. Components should keep an emoji/colour fallback.
export const libUrl = (category: string, file: string) => `${ASSET_BASE}/${category}/${file}.png`;

// Game item name -> { category, file } sprite. Falls back to a per-type sprite.
const ITEM_BY_NAME: Record<string, [string, string]> = {
  "Bois": ["objects", "mat-wood"],
  "Pierre": ["objects", "mat-stone"],
  "Minerai de fer": ["objects", "mat-ironore"],
  "Ration d'eau": ["objects", "food-waterflask"],
  "Viande": ["objects", "food-meat"],
  "Fleur": ["props", "prop-flowers"],
  "Herbe médicinale": ["objects", "med-herbs"],
  "Potion de soin": ["objects", "potion-red"],
  "Jus de fruit": ["objects", "potion-green"],
  "Lame de fer": ["objects", "weapon-dagger"],
  "Totem de bois": ["objects", "obj-crate"],
  "Mapo Curry": ["objects", "food-meat"],
};
const ITEM_BY_TYPE: Record<string, [string, string]> = {
  aliment: ["objects", "food-bread"],
  eau: ["objects", "food-waterflask"],
  plante: ["objects", "med-herbs"],
  minerai: ["objects", "mat-stone"],
  objet: ["objects", "obj-crate"],
  arme: ["objects", "weapon-sword"],
  consommable: ["objects", "potion-red"],
  deco: ["objects", "mat-wood"],
};
export function itemAssetUrl(item: { type: string; name: string }): string | undefined {
  const m = ITEM_BY_NAME[item.name] ?? ITEM_BY_TYPE[item.type];
  return m ? libUrl(m[0], m[1]) : undefined;
}

// Monster species -> creature sprite. (Keyed without accents too, to be safe.)
const MONSTER_BY_SPECIES: Record<string, string> = {
  "Goblin Pillard": "mob-goblin",
  "Slime Vorace": "mob-slime",
  "Elementaire de Vent": "mob-windelemental",
  "Élémentaire de Vent": "mob-windelemental",
};
export function monsterAssetUrl(species: string): string | undefined {
  const f = MONSTER_BY_SPECIES[species];
  return f ? libUrl("monsters", f) : undefined;
}
export const monsterTexKey = (species: string): string | undefined => MONSTER_BY_SPECIES[species];

// Hero class -> chibi character sprite (for map/combat tokens). Defaults to the scout.
const HERO_BY_CLASS: Record<string, string> = {
  "Sans classe": "char-scout",
  "Pionnier": "char-builder",
  "Chasseur": "char-archer",
  "Éclaireur": "char-scout",
  "Gardien": "char-knight",
  "Récupérateur": "char-merchant",
  "Herboriste": "char-healer",
};
export const HERO_TEX_KEYS = ["char-scout", "char-builder", "char-archer", "char-knight", "char-merchant", "char-healer", "char-wizard"];
export const heroTexKey = (cls?: string): string => (cls && HERO_BY_CLASS[cls]) || "char-scout";
export function heroAssetUrl(cls?: string): string {
  return libUrl("characters", heroTexKey(cls));
}
