// Asset registry: maps asset keys to their public URL.
// Files live in frontend/public/assets/ and are generated by scripts/generate-assets.mjs.
// If an asset hasn't been generated yet, the component falls back to its emoji placeholder.
//
// To add a new asset: add the entry here, add it to scripts/asset-manifest.mjs,
// then re-run the generator.

export const ASSET_BASE = "/assets";

export type AssetKey =
  // buildings
  | "building-gate" | "building-wall" | "building-bank" | "building-well"
  | "building-workshop" | "building-tower" | "building-townhall"
  | "building-kitchen" | "building-panel" | "building-scaffold"
  // heroes
  | "hero-sans-classe" | "hero-pionnier" | "hero-chasseur" | "hero-eclaireur"
  | "hero-gardien" | "hero-recuperateur" | "hero-herboriste"
  // ui
  | "nav-home" | "nav-map" | "nav-stock" | "nav-structure" | "nav-craft"
  | "bird" | "skull"
  // npc / bg
  | "shinki-npc" | "town-island" | "app-bg" | "bridge"
  // map tiles (one per biome 0..5)
  | "tile-water" | "tile-sand" | "tile-grass" | "tile-forest" | "tile-mountain" | "tile-snow"
  // isometric cube tiles (iso Home grid + iso combat biomes)
  | "iso-water" | "iso-sand" | "iso-grass" | "iso-forest" | "iso-stone" | "iso-snow" | "iso-bridge";

const PATHS: Record<AssetKey, string> = {
  "building-gate":      `${ASSET_BASE}/buildings/gate.png`,
  "building-wall":      `${ASSET_BASE}/buildings/wall.png`,
  "building-bank":      `${ASSET_BASE}/buildings/bank.png`,
  "building-well":      `${ASSET_BASE}/buildings/well.png`,
  "building-workshop":  `${ASSET_BASE}/buildings/workshop.png`,
  "building-tower":     `${ASSET_BASE}/buildings/tower.png`,
  "building-townhall":  `${ASSET_BASE}/buildings/townhall.png`,
  "building-kitchen":   `${ASSET_BASE}/buildings/kitchen.png`,
  "building-panel":     `${ASSET_BASE}/buildings/panel.png`,
  "building-scaffold":  `${ASSET_BASE}/buildings/scaffold.png`,

  "hero-sans-classe":   `${ASSET_BASE}/heroes/hero-0.png`,
  "hero-pionnier":      `${ASSET_BASE}/heroes/hero-pionnier.png`,
  "hero-chasseur":      `${ASSET_BASE}/heroes/hero-chasseur.png`,
  "hero-eclaireur":     `${ASSET_BASE}/heroes/hero-eclaireur.png`,
  "hero-gardien":       `${ASSET_BASE}/heroes/hero-gardien.png`,
  "hero-recuperateur":  `${ASSET_BASE}/heroes/hero-recuperateur.png`,
  "hero-herboriste":    `${ASSET_BASE}/heroes/hero-herboriste.png`,

  "nav-home":      `${ASSET_BASE}/ui/nav-home.png`,
  "nav-map":       `${ASSET_BASE}/ui/nav-map.png`,
  "nav-stock":     `${ASSET_BASE}/ui/nav-stock.png`,
  "nav-structure": `${ASSET_BASE}/ui/nav-structure.png`,
  "nav-craft":     `${ASSET_BASE}/ui/nav-craft.png`,
  "bird":          `${ASSET_BASE}/ui/bird.png`,
  "skull":         `${ASSET_BASE}/ui/skull.png`,

  "shinki-npc":   `${ASSET_BASE}/npc/shinki.png`,
  "town-island":  `${ASSET_BASE}/bg/town-island.png`,
  "app-bg":       `${ASSET_BASE}/bg/app-bg.png`,
  "bridge":       `${ASSET_BASE}/bg/bridge.png`,

  "tile-water":    `${ASSET_BASE}/tiles/water.png`,
  "tile-sand":     `${ASSET_BASE}/tiles/sand.png`,
  "tile-grass":    `${ASSET_BASE}/tiles/grass.png`,
  "tile-forest":   `${ASSET_BASE}/tiles/forest.png`,
  "tile-mountain": `${ASSET_BASE}/tiles/mountain.png`,
  "tile-snow":     `${ASSET_BASE}/tiles/snow.png`,

  "iso-water":    `${ASSET_BASE}/isotiles/water.png`,
  "iso-sand":     `${ASSET_BASE}/isotiles/sand.png`,
  "iso-grass":    `${ASSET_BASE}/isotiles/grass.png`,
  "iso-forest":   `${ASSET_BASE}/isotiles/forest.png`,
  "iso-stone":    `${ASSET_BASE}/isotiles/stone.png`,
  "iso-snow":     `${ASSET_BASE}/isotiles/snow.png`,
  "iso-bridge":   `${ASSET_BASE}/isotiles/bridge.png`,
};

// Resolved set of available assets (populated at startup by probing HEAD requests).
// During SSR / before detection completes, all assets are considered unavailable
// so components fall back to their emoji placeholders.
const available = new Set<AssetKey>();

export function assetUrl(key: AssetKey): string | undefined {
  return available.has(key) ? PATHS[key] : undefined;
}

// Called once at app start. Probes which assets exist so components can switch
// from emoji fallbacks to real images.
export async function detectAvailableAssets(): Promise<void> {
  const checks = Object.entries(PATHS) as [AssetKey, string][];
  await Promise.allSettled(
    checks.map(async ([key, url]) => {
      try {
        const r = await fetch(url, { method: "HEAD" });
        if (r.ok) available.add(key);
      } catch {}
    }),
  );
}
